version: '3'
services:

  aeternity:
    image: "aeternity/epoch:latest"
    ports:
      - "3013:3013"
      - "3015:3015"
      - "3113:3113"
    command: "-aehttp enable_debug_endpoints true"
    volumes:
      - "./docker/epoch.yaml:/home/epoch/.epoch/epoch/epoch.yaml"
      - "./docker/db:/home/epoch/node/data/mnesia"

  ipfs:
    image: "ipfs/go-ipfs:latest"
    ports:
      - "4001:4001"
      - "5001:5001"
      - "8080:8080"
    volumes:
      - "./docker/ipfs:/data/ipfs"
